version: "3.3"

services:
  note-hub:
    build: .
    container_name: 'golang'
    restart: always
    ports:
      - '8080:8080'
    depends_on: 
      - database
    networks:
      - network
  database:
    image: 'postgres'
    container_name: 'postgres'
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5432:5432'
    networks:
      - network

networks:
  network:
    driver: bridge
